[package]
name = "rust_utils"
version = "0.1.0"
edition = "2021"

[dependencies]
ractor = {version = "0.14.5", optional = true}
libm = "0.2.11"
chrono = "0.4.39"
sea-orm = {version = "1.1.4", optional = true}
serde = {version = "1.0.217", features = ["default", "derive"], optional = true}
serde_json = {version = "1.0.138", optional = true}
rand = {version = "0.9.0", optional = true}
md5 = {version = "0.7.0", optional = true}

[features]
database_expand = ["sea-orm", "serde", "serde_json"]
encrypt = ["rand", "md5"]
